dependencies:
  - pip:
      - redshift-connector==2.1.3
      - sshtunnel==0.4.0
      - pgpy==0.6.0
      - psycopg2==2.9.3
      - pyzipper==0.3.6
      - openpyxl==3.1.5
      - pyodbc==5.1.0
      - intuit-oauth==1.2.6
      - psycopg2-binary==2.9.3
